### ISSUE TITLE
Bot uptime improvement using third-party dependency

### ISSUE THREAD

**Issue by LocalCodes** [suggestionsbot/suggestions-bot#34]
You can improve or simplify the uptime section of `stats.js` using `moment` and `moment-duration-format` as follows:

**Requires**
```js
const moment = require("moment");
require("moment-duration-format");
```

**Official "Implementation"**
```js
const duration = moment.duration(client.uptime).format(" D [days], H [hrs], m [mins], s [secs]");
console.log(duration); // Display wherever, however.
```

**Comment by acollierr17** [comment]
I actually removed `moment.js` and other dependencies I didn't seem necessary anymore. Nowadays, I don't add on dependencies that don't actually have a *real* use for. The examples you showed above are **exactly** what I used to use (check out the codebase while you're at it).

If you look at the utils file, I have a couple of date/time-related functions in there that I find a lot better than adding entire packages just to use one or two functions. Again, if you can simply write the single function yourself instead of adding an entire package, go for that instead.

If you have any further questions about this, feel free to ask, but I'll be going ahead and closing this ticket.
